local:
  image: brunolm/node-image:7.4.0-onbuild
  command: npm run dev
  environment:
    NODE_ENV: development
    BOT_NAME: genos
    BOT_TOKEN: #
  volumes:
    - './:/usr/src/app'

ci:
  build: .
  command: npm test
