local:
  image: node:8.5.0
  command: npm run dev
  working_dir: /usr/src/app
  environment:
    NODE_ENV: development
    BOT_NAME: genos
    BOT_TOKEN: #
  volumes:
    - './:/usr/src/app'

ci:
  build: .
  command: npm test
